### ISSUE TITLE
二屏各种init service狗带

### ISSUE THREAD

**Issue by GuaiYiHu** [tiger-cave/device_xiaomi_msm8960-common#2]
Dmesg
[   62.805328] init: Starting service 'sensors'...
[   62.805938] init: Starting service 'ppd'...
[   62.806396] init: Starting service 'qcamerasvr'...
[   62.810699] init: Service 'ppd' (pid 2623) exited with status 1
[   62.810729] init: Service 'ppd' (pid 2623) killing any children in process group
[   62.814910] init: Service 'qcamerasvr' (pid 2624) exited with status 1
[   62.814971] init: Service 'qcamerasvr' (pid 2624) killing any children in process group
[   62.900604] ch_notify on a closed smd_pkt_dev id:18
[   62.904022] init: Service 'sensors' (pid 2622) killed by signal 6
[   62.904052] init: Service 'sensors' (pid 2622) killing any children in process group
[   66.307342] init: Starting service 'ril-daemon'...
[   66.333099] init: Service 'ril-daemon' (pid 2671) exited with status 1
[   66.333129] init: Service 'ril-daemon' (pid 2671) killing any children in process group
[   66.526611] acc_open
[   66.526641] acc_release
[   67.673461] init: Starting service 'sensors'...
[   67.674133] init: Starting service 'ppd'...
[   67.674591] init: Starting service 'qcamerasvr'...
[   67.680206] init: Service 'ppd' (pid 2697) exited with status 1
[   67.680236] init: Service 'ppd' (pid 2697) killing any children in process group
[   67.680664] init: Service 'qcamerasvr' (pid 2698) exited with status 1
[   67.680694] init: Service 'qcamerasvr' (pid 2698) killing any children in process group
[   67.780303] ch_notify on a closed smd_pkt_dev id:18
[   68.522918] init: Service 'sensors' (pid 2696) killed by signal 6
[   68.522979] init: Service 'sensors' (pid 2696) killing any children in process group
[   68.553405] binder: 1825:62 delete ref 2604 desc 0 for node 1 node proc 440 s 1 w 1 d   (null)
[   68.554840] binder: 441:899 transaction failed 29189, size 68-0
[   68.556457] init: Starting service 'bootanim'...
[   68.692810] alarm_release: clear alarm, pending 0
[   68.963165] init: Service 'zygote' (pid 526) killed by signal 9
[   68.963226] init: Service 'zygote' (pid 526) killing any children in process group
[   68.963531] init: write_file: Unable to open '/sys/android_power/request_state': No such file or directory
[   68.963714] request_suspend_state: wakeup (0->0) at 68962791134 (2017-08-15 06:34:26.416346474 UTC)
[   68.963806] init: Service 'media' is being killed...
[   68.966735] init: Service 'netd' is being killed...
[   68.969360] init: Starting service 'zygote'...
[   68.976470] init: Service 'netd' (pid 513) killed by signal 9
[   68.976501] init: Service 'netd' (pid 513) killing any children in process group
[   68.977294] init: Starting service 'netd'...
[   68.977386] binder: 518:62 delete ref 32 desc 0 for node 1 node proc 440 s 1 w 1 d   (null)
[   68.981079] init: Service 'media' (pid 518) killed by signal 9
[   68.981079] init: Service 'media' (pid 518) killing any children in process group
[   68.981689] init: Starting service 'media'...

**Comment by GuaiYiHu** [comment]
logcat
08-15 07:01:30.275  4606  4606 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfffffffe in tid 4606 (system_server)
08-15 07:01:30.278   500   500 I DEBUG   : property debug.db.uid not set; NOT waiting for gdb.
08-15 07:01:30.278   500   500 I DEBUG   : HINT: adb shell setprop debug.db.uid 100000
08-15 07:01:30.278   500   500 I DEBUG   : HINT: adb forward tcp:5039 tcp:5039
08-15 07:01:30.382   500   500 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
08-15 07:01:30.382   500   500 F DEBUG   : LineageOS Version: '13.0-20170815-UNOFFICIAL-aries'
08-15 07:01:30.382   500   500 F DEBUG   : Build fingerprint: 'Xiaomi/lineage_aries/aries:6.0.1/MOB31T/e745266796:userdebug/test-keys'
08-15 07:01:30.382   500   500 F DEBUG   : Revision: '0'
08-15 07:01:30.382   500   500 F DEBUG   : ABI: 'arm'
08-15 07:01:30.383   500   500 F DEBUG   : pid: 4606, tid: 4606, name: system_server  >>> system_server <<<
08-15 07:01:30.383   500   500 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xfffffffe
08-15 07:01:30.424   500   500 F DEBUG   :     r0 9fd0d010  r1 00001000  r2 00001000  r3 ffffffff
08-15 07:01:30.424   500   500 F DEBUG   :     r4 00000000  r5 12dd57a0  r6 12dd57a0  r7 9e707d58
08-15 07:01:30.424   500   500 F DEBUG   :     r8 12e20d80  r9 b8493230  sl 00001000  fp 00000002
08-15 07:01:30.424   500   500 F DEBUG   :     ip b3746395  sp befc9ea0  lr a1218567  pc fffffffe  cpsr 600f0030
08-15 07:01:30.428   500   500 F DEBUG   : 
08-15 07:01:30.428   500   500 F DEBUG   : backtrace:
08-15 07:01:30.428   500   500 F DEBUG   :     #00 pc fffffffe  <unknown>
08-15 07:01:30.428   500   500 F DEBUG   :     #01 pc 00c68565  /data/dalvik-cache/arm/system@framework@services.jar@classes.dex (offset 0x810000)
08-15 07:01:31.741   500   500 F DEBUG   : 
08-15 07:01:31.741   500   500 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_01
08-15 07:01:31.769   505   505 E installd: eof
08-15 07:01:31.769   505   505 E installd: failed to read size

**Comment by iamOJZ** [comment]
开机还有希望不😂

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi MI 2S 发送_

**Comment by GuaiYiHu** [comment]
分析： sensors以及ppd service exit导致zygote 也跟着exit
而所有服务都go die的根本原因推测是
avc: denied { entrypoint } for pid=564 comm="init" path="*******" dev="mmcblk0p21" ino=331 scontext=u:r:mpdecision:s0 tcontext=u:object_r:system_file:s0 tclass=file permissive=1
可供参考的commit：
https://github.com/SlimRoms/device_samsung_i9100g/commit/cf694c0749352d540b67130c5aedcfc32fd8ed39
推测，将文件补到file_context即可解决
参考资料：
http://www.jianshu.com/p/dcbd35410078

**Comment by iamOJZ** [comment]
通宵搞，辛苦了

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi MI 2S 发送_

**Comment by GuaiYiHu** [comment]
死掉的服务都是需要a SELinux domain defined; please fix!的服务==
https://github.com/MoKee/android_device_samsung_ha3g/commit/6ac84cd867066dbfc8130833f29e9c1a40b8b2a1
