### ISSUE TITLE
service sensor ppd go die

### ISSUE THREAD

**Issue by GuaiYiHu** [tiger-cave/device_xiaomi_msm8960-common#7]
[  138.960021] init: Service 'sensors' (pid 3796) killed by signal 6
[  138.965087] init: Service 'sensors' (pid 3796) killing any children in process group
[  140.978851] init: Warning!  Service thermald_l needs a SELinux domain defined; please fix!
[  140.986145] init: Starting service 'thermald_l'...
[  140.993896] init: Warning!  Service ppd needs a SELinux domain defined; please fix!
[  141.003570] init: Starting service 'ppd'...
[  141.031311] init: Service 'ppd' (pid 3806) exited with status 1
[  141.036285] init: Service 'ppd' (pid 3806) killing any children in process group

**Comment by GuaiYiHu** [comment]
ppd好像可以删掉，没啥用，还是从oppo弄过来的

**Comment by nitin1438** [comment]
Any solution for this error in dmesg?
